name: myapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  table_calendar: ^3.1.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  intl: ^0.19.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  geolocator: ^11.0.0 # Added for getting device location

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
