name: myapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  table_calendar: ^3.1.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  intl: ^0.19.0
  uuid: ^4.4.0 # Added for unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
