// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbcQFYYKirzwKsmUFlBflcij9nrW_cdRU',
    appId: '1:123406747069:web:8d2fb272d1850f95eabed4',
    messagingSenderId: '123406747069',
    projectId: 'myapp-7804a',
    authDomain: 'myapp-7804a.firebaseapp.com',
    storageBucket: 'myapp-7804a.firebasestorage.app',
    measurementId: 'G-B0N03FSW50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFzNt2y-56XyJfYq-dx19IfaBLFY4WO3s',
    appId: '1:123406747069:android:2103f53b49984b7ceabed4',
    messagingSenderId: '123406747069',
    projectId: 'myapp-7804a',
    storageBucket: 'myapp-7804a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXejyAZUnj3AG-LI8PrAhCEpv5bjqLHSc',
    appId: '1:123406747069:ios:14324279f068dd4beabed4',
    messagingSenderId: '123406747069',
    projectId: 'myapp-7804a',
    storageBucket: 'myapp-7804a.firebasestorage.app',
    iosClientId: '123406747069-iljmtrlkgtoosb33ibs2lpgo0rsc2ci2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXejyAZUnj3AG-LI8PrAhCEpv5bjqLHSc',
    appId: '1:123406747069:ios:14324279f068dd4beabed4',
    messagingSenderId: '123406747069',
    projectId: 'myapp-7804a',
    storageBucket: 'myapp-7804a.firebasestorage.app',
    iosClientId: '123406747069-iljmtrlkgtoosb33ibs2lpgo0rsc2ci2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbcQFYYKirzwKsmUFlBflcij9nrW_cdRU',
    appId: '1:123406747069:web:b0b6db4d2b971aabeabed4',
    messagingSenderId: '123406747069',
    projectId: 'myapp-7804a',
    authDomain: 'myapp-7804a.firebaseapp.com',
    storageBucket: 'myapp-7804a.firebasestorage.app',
    measurementId: 'G-SRJD74PZFQ',
  );
}
